name: Build Wheels and Upload to Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "mdk-python/**.py"
      - "mtlcc/**.py"
jobs:
  build-mdk-wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - run: |
          # 1.1b1 breakpoint/passpoint functions
          nasm -o mtlcc/asm/1.1b1/breakpoint.bin mtlcc/asm/1.1b1/breakpoint.asm
          nasm -o mtlcc/asm/1.1b1/passpoint.bin mtlcc/asm/1.1b1/passpoint.asm
          python3 .github/copy_binary.py mtlcc/asm/1.1b1/breakpoint.bin mtlcc/mtl/debugging/asmbin/breakpoint_11b1.py BREAKPOINT_FUNC_11B1
          python3 .github/copy_binary.py mtlcc/asm/1.1b1/passpoint.bin mtlcc/mtl/debugging/asmbin/passpoint_11b1.py PASSPOINT_FUNC_11B1
      - run: python3 -m pip install --upgrade pip build
      - run: cd mtlcc && python3 -m build
      - run: cd mdk-python && python3 -m build
      - run: mkdir dist && cp mtlcc/dist/* dist/ && cp mdk-python/dist/* dist/
      - uses: actions/upload-artifact@v4
        with:
          name: mdk-latest
          path: dist

